import { IconSUN } from '../system';
import {
    IconAAVE,
    IconAELF,
    IconAIRI,
    IconALGO,
    IconAPT,
    IconAR,
    IconARB,
    IconATOM,
    IconAUSDT,
    IconAVAX,
    IconAXS,
    IconBNB,
    IconBONK,
    IconBTC,
    IconBTCB,
    IconBTT,
    IconBUSD,
    IconCOMP,
    IconDAI,
    IconDOGE,
    IconEDU,
    IconETH,
    IconFDUSD,
    IconFIL,
    IconFLOKI,
    IconFLOW,
    IconFLUX,
    IconGALA,
    IconGNO,
    IconGRT,
    IconHBAR,
    IconHNT,
    IconHOT,
    IconHT,
    IconHTX,
    IconIMX,
    IconINJ,
    IconION,
    IconIOTX,
    IconJASMY,
    IconJST,
    IconJUP,
    IconKAS,
    IconKCS,
    IconKWT,
    IconLTC,
    IconMANA,
    IconMETIS,
    IconMILKY,
    IconMINA,
    IconMKR,
    IconNEO,
    IconNEXO,
    IconNFT,
    IconNTMPI,
    IconOCH,
    IconORAI,
    IconOSMO,
    IconOraiX,
    IconPEPE,
    IconPYTH,
    IconROSE,
    IconSCATOM,
    IconSCORAI,
    IconSCOSMO,
    IconSHIBAINU,
    IconSNX,
    IconSOL,
    IconSORAI,
    IconSTATOM,
    IconSTOSMO,
    IconSTRX,
    IconSTUSDT,
    IconSTX,
    IconSUNOLD,
    IconScINJ,
    IconTIA,
    IconTON,
    IconTRX,
    IconTUSD,
    IconUSDC,
    IconUSDD,
    IconUSDJ,
    IconUSDT,
    IconVET,
    IconWBTC,
    IconWEDU,
    IconWIF,
    IconWIN,
    IconXLM,
    IconXMR,
    IconXOCH,
    IconXRP,
    IconZEC,
    IconZRX,
} from '../token';
import { SvgComponent, TokenName } from '../types';

export const mapNameToIcon: Record<TokenName, SvgComponent> = {
    HT: IconHT,
    HTX: IconHTX,
    JST: IconJST,
    BNB: IconBNB,
    BTC: IconBTC,
    ETH: IconETH,
    OCH: IconOCH,
    STRX: IconSTRX,
    USDC: IconUSDC,
    USDD: IconUSDD,
    USDT: IconUSDT,
    xOCH: IconXOCH,
    INJ: IconINJ,
    ORAI: IconORAI,
    OSMO: IconOSMO,
    scOSMO: IconSCOSMO,
    scINJ: IconScINJ,
    scORAI: IconSCORAI,
    sORAI: IconSORAI,
    TRX: IconTRX,
    USDJ: IconUSDJ,
    SUN: IconSUN,
    SUNOLD: IconSUNOLD,
    ATOM: IconATOM,
    scATOM: IconSCATOM,
    WIN: IconWIN,
    DAI: IconDAI,
    MILKY: IconMILKY,
    LTC: IconLTC,
    NFT: IconNFT,
    NTMPI: IconNTMPI,
    KWT: IconKWT,
    TUSD: IconTUSD,
    AIRI: IconAIRI,
    wTRX: IconTRX,
    WBTC: IconWBTC,
    WETH: IconETH,
    BUSD: IconBUSD,
    BTT: IconBTT,
    STUSDT: IconSTUSDT,
    wstUSDT: IconSTUSDT,
    APT: IconAPT,
    AR: IconAR,
    ARB: IconARB,
    IMX: IconIMX,
    SHIBAINU: IconSHIBAINU,
    SOL: IconSOL,
    VET: IconVET,
    XLM: IconXLM,
    XRP: IconXRP,
    ALGO: IconALGO,
    AVAX: IconAVAX,
    FLOW: IconFLOW,
    GALA: IconGALA,
    NEO: IconNEO,
    NEXO: IconNEXO,
    MANA: IconMANA,
    MINA: IconMINA,
    SNX: IconSNX,
    ROSE: IconROSE,
    AELF: IconAELF,
    COMP: IconCOMP,
    FLUX: IconFLUX,
    GNO: IconGNO,
    HOT: IconHOT,
    IOTX: IconIOTX,
    METIS: IconMETIS,
    ZEC: IconZEC,
    ZRX: IconZRX,
    DOGE: IconDOGE,
    TON: IconTON,
    EDU: IconEDU,
    KAS: IconKAS,
    PEPE: IconPEPE,
    XMR: IconXMR,
    FDUSD: IconFDUSD,
    STX: IconSTX,
    FIL: IconFIL,
    HBAR: IconHBAR,
    MKR: IconMKR,
    AAVE: IconAAVE,
    WIF: IconWIF,
    GRT: IconGRT,
    HNT: IconHNT,
    BONK: IconBONK,
    FLOKI: IconFLOKI,
    TIA: IconTIA,
    WEDU: IconWEDU,
    JUP: IconJUP,
    JASMY: IconJASMY,
    PYTH: IconPYTH,
    KCS: IconKCS,
    AXS: IconAXS,
    ORAIX: IconOraiX,
    aUSDT: IconAUSDT,
    stATOM: IconSTATOM,
    stOSMO: IconSTOSMO,
    BTCB: IconBTCB,

    WBNB: IconBNB,
    ETHOLD: IconETH,
    WBTT: IconBTT,
    ION: IconION,
};
