import { IconSUN } from '../system';
import {
    IconAIRI,
    IconALGO,
    IconAPT,
    IconAR,
    IconARB,
    IconATOM,
    IconAVAX,
    IconBNB,
    IconBTC,
    IconBTT,
    IconBUSD,
    IconDAI,
    IconETH,
    IconFLOW,
    IconGALA,
    IconHT,
    IconHTX,
    IconIMX,
    IconINJ,
    IconJST,
    IconKWT,
    IconLTC,
    IconMILKY,
    IconNEO,
    IconNEXO,
    IconNFT,
    IconNTMPI,
    IconOCH,
    IconORAI,
    IconOSMO,
    IconSCATOM,
    IconSCORAI,
    IconSCOSMO,
    IconSHIBAINU,
    IconSOL,
    IconSORAI,
    IconSTRX,
    IconSTUSDT,
    IconSUNOLD,
    IconScINJ,
    IconTRX,
    IconTUSD,
    IconUSDC,
    IconUSDD,
    IconUSDJ,
    IconUSDT,
    IconVET,
    IconWBTC,
    IconWIN,
    IconXLM,
    IconXOCH,
    IconXRP,
} from '../token';
import { SvgComponent, TokenName } from '../types';

export const mapNameToIcon: Record<TokenName, SvgComponent> = {
    HT: IconHT,
    HTX: IconHTX,
    JST: IconJST,
    BNB: IconBNB,
    BTC: IconBTC,
    ETH: IconETH,
    OCH: IconOCH,
    STRX: IconSTRX,
    USDC: IconUSDC,
    USDD: IconUSDD,
    USDT: IconUSDT,
    xOCH: IconXOCH,
    INJ: IconINJ,
    ORAI: IconORAI,
    OSMO: IconOSMO,
    scOSMO: IconSCOSMO,
    scINJ: IconScINJ,
    scORAI: IconSCORAI,
    sORAI: IconSORAI,
    TRX: IconTRX,
    USDJ: IconUSDJ,
    SUN: IconSUN,
    SUNOLD: IconSUNOLD,
    ATOM: IconATOM,
    scATOM: IconSCATOM,
    WIN: IconWIN,
    DAI: IconDAI,
    MILKY: IconMILKY,
    LTC: IconLTC,
    NFT: IconNFT,
    NTMPI: IconNTMPI,
    KWT: IconKWT,
    TUSD: IconTUSD,
    AIRI: IconAIRI,
    WTRX: IconTRX,
    WBTC: IconWBTC,
    WETH: IconETH,
    BUSD: IconBUSD,
    BTT: IconBTT,
    STUSDT: IconSTUSDT,
    wstUSDT: IconSTUSDT,
    APT: IconAPT,
    AR: IconAR,
    ARB: IconARB,
    IMX: IconIMX,
    SHIBAINU: IconSHIBAINU,
    SOL: IconSOL,
    VET: IconVET,
    XLM: IconXLM,
    XRP: IconXRP,
    ALGO: IconALGO,
    AVAX: IconAVAX,
    FLOW: IconFLOW,
    GALA: IconGALA,
    NEO: IconNEO,
    NEXO: IconNEXO,
};
